<?php

namespace AppBundle\Repository;

/**
 * SpeedTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeedTestRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLatestByDate($fromDate, $limit){
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.timestamp >= :fromDate')
            ->setParameter('fromDate', $fromDate)
            ->orderBy('e.timestamp', 'desc')
            ->setMaxResults($limit)
            ->getQuery();

        return $q->getResult();
    }

    public function findFastestByDate($fromDate, $limit){
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.timestamp >= :fromDate')
            ->setParameter('fromDate', $fromDate)
            ->orderBy('e.downloadSpeed', 'desc')
            ->setMaxResults($limit)
            ->getQuery();

        return $q->getResult();
    }

    public function findFastestProviderByDate($fromDate, $limit){
        $q = $this
            ->createQueryBuilder('e')
            ->select('AVG(e.downloadSpeed) as median, e.provider')
            ->where('e.timestamp >= :fromDate')
            ->setParameter('fromDate', $fromDate)
            ->groupBy('e.provider')
            ->orderBy('median', 'desc')
            ->setMaxResults($limit)
            ->getQuery();

        return $q->getResult();
    }
}
